import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable}  antialiased overflow-x-hidden bg-(--background) text-(--primary-text)`}>
        <div className="w-screen h-fit ">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
